# Dependencies
markdown:         kramdown
highlighter:      pygments

# Gems
gems: [jekyll-paginate, jekyll-gist]

# Permalinks
permalink:        pretty

# Setup
title:            Inpad
tagline:          'Inpad app'
description:      'A Notes App with Github Flavored Markdown'
url:              http://sarah-seo.github.io/Inpad
baseurl:          /Inpad

author:
  name:           'Sarah Seo'
  url:            https://github.com/sarah-seo

paginate:         5

# Custom vars
version:          0.1.0

github:
  repo:           https://github.com/sarah-seo/Inpad
